#Virtual host de HRjuandragontech.local. Primero pongo el puerto al que escucha
<VirtualHost *:13>
    #Dominio principal al que corresponde este bloque:
    ServerName HRjuandragontech.local

    #Alias por si entran con las www
    ServerAlias www.HRjuandragontech.local

    #Ruta exacta del contenedor donde esta el index.html
    DocumentRoot /usr/local/apache2/htdocs/HRjuandragontech.local

    #Guarda los errores separados de los demas
    ErrorLog logs/HRjuandragontech_error.log

    #Le doy permisos a todos para leer los archivos de la carpeta
    <Directory /usr/local/apache2/htdocs/HRjuandragontech.local>
        Require all granted
    </Directory>

</VirtualHost>

#Virtual host de HRshadowbyte.local. Primero pongo el puerto al que escucha
<VirtualHost *:13>
    #Dominio principal al que corresponde este bloque:
    ServerName HRshadowbyte.local

    #Alias por si entran con las www
    ServerAlias www.HRshadowbyte.local

    #Ruta exacta del contenedor donde esta el index.html
    DocumentRoot /usr/local/apache2/htdocs/HRshadowbyte.local

    #Guarda los errores separados de los demas
    ErrorLog logs/HRshadowbyte_error.log

    #Bloquear un archivo
    <Files "configurar.php">
            Require all denied
    </Files>

    #Le doy permisos a todos para leer los archivos de la carpeta
    <Directory /usr/local/apache2/htdocs/HRshadowbyte.local>
        Require all granted
         #Ocultar all granted
        Options -Indexes
    </Directory>

</VirtualHost>
